#
# Travis CI control file for building Phoenix
#

language: python
    
python: 
    - "2.7"
    #- "3.4"  # Just do one Python for now.
    
sudo: false
    
    
# Available build steps:
# 1. before_install
# 2. install
# 3. before_script
# 4. script
# 5. after_success or after_failure
# 6. after_script
# 7. OPTIONAL before_deploy
# 8. OPTIONAL deploy
# 9. OPTIONAL after_deploy



addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev


install:
    - echo "****** travis install step"
    - pip install -U pip
    - pip install -U -r requirements.txt
    - pip list


script:
    - echo "****** travis script step"
    - python build.py dox
    - python build.py build_wx --jobs=4
    - python build.py etg --nodoc
    - python build.py sip
    - python build.py build_py --jobs=4
    # TODO: Add running of the tests
    
    
    
